/**
 * AI API — tutor / copilot / teaching-assistant conversation surfaces.
 *
 * Replies are generated by the deterministic prototype reply engines
 * (./tutor-reply, ./assistant-reply) — clearly prototype intelligence, not a
 * live model. Endpoint contracts unchanged.
 */
import { defineRoute } from '../core/router'
import {
  aiTutorThreads, aiTutorQuickPrompts, copilotSuggestions, aiTeachingAssistantThreads,
  learningPath,
  graphSearch, aiConversationStats,
} from '@/datasets/ai/assistants.js'
import { generateAssistantReply } from './assistant-reply'
import { generateTutorReply } from './tutor-reply'

/* ---------------- AI ---------------- */
defineRoute('get', '/ai/tutor/threads', () => ({ threads: aiTutorThreads, quickPrompts: aiTutorQuickPrompts }))
/* Phase 3 — retired GET /ai/tutor/threads/:id (the tutor page dereferences
   threads from the list payload). */
defineRoute('post', '/ai/tutor/respond', ({ body }) => ({ reply: generateTutorReply(body?.text || ''), threadId: body?.threadId || 'new' }))
defineRoute('get', '/ai/copilot/suggestions', ({ params }) => ({
  suggestions: copilotSuggestions[params?.path] ?? copilotSuggestions['/student'],
}))
defineRoute('get', '/ai/learning-path', () => learningPath)
/* Phase 3 — retired unused AI reads (recommendations/weaknesses/prediction);
   AI surfaces consume tutor/copilot/assistant threads + intelligence. */
defineRoute('get', '/ai/graph-search', ({ params }) => ({ ...graphSearch, query: params?.q || '' }))
defineRoute('get', '/ai/assistant/threads', () => ({ threads: aiTeachingAssistantThreads }))
/* Assistant replies are simulated (frontend-only prototype) — the reply
   generator is contextual and conversation messages persist into the
   shared dataset so history survives refetch/reload. */
defineRoute('post', '/ai/assistant/respond', ({ body }) => {
  const text = String(body?.text ?? '').trim()
  const reply = generateAssistantReply(text)
  const thread = aiTeachingAssistantThreads[0]
  if (thread) {
    thread.messages.push(
      { id: `u_${Date.now()}`, role: 'user', text, time: new Date().toISOString() },
      { id: `a_${Date.now()}`, role: 'assistant', text: reply, time: new Date().toISOString() }
    )
    thread.updated = 'just now'
  }
  return { reply }
})
/* Phase 3 — retired unused AI quiz/exam generation endpoints (the builder
   pages use /faculty/quiz-builder and /faculty/exam-builder services). */
defineRoute('get', '/ai/stats', () => aiConversationStats)

/* ---------------- Shared lookup ---------------- */
/* Phase 2 cleanup: the legacy `/directory/*` endpoints had no service, hook,
   page or component consumer (they predate the services layer). The datasets
   they served (STUDENT_ROSTER, FACULTY_LIST, ADMIN_USERS) remain authoritative
   via direct imports in the intelligence datasets. */
