import { useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowUp, Bot, Maximize2, Sparkles, X } from 'lucide-react'
import { useCopilotSuggestions, useAITutorRespond } from '@/services'
import { generateTutorReply } from '@/api/mock-routes'
import { ChatMessage, TypingDots } from '@/components/shared/chat-message'
import { useToast } from '@/components/ui'

const COPIED_INTRO = {
  student: 'Hi Aarav! 👋 I’m MediXO Mentor — I can explain concepts, plan your day, quiz you, or help with assignments. What are we tackling?',
  faculty: 'Welcome back, Dr. Krishnan! I’m MediXO Mentor — I can draft quizzes, pre-grade submissions, plan lectures or analyse your class. What do you need?',
  admin: 'Good day! I’m MediXO Mentor — I can summarise institutional trends, draft reports or dig into analytics. Ask me anything.',
  parent: 'Hello! I’m MediXO Mentor — I can translate reports into plain language, summarise your ward’s week, or suggest what to ask teachers.',
}

function AICopilotFab({ open, onOpenChange, role, onNavigate }) {
  const location = useLocation()
  const navigate = useNavigate()
  const toast = useToast()
  // Students open the unified MediXO Mentor workspace; faculty open the AI
  // Teaching Assistant; admin opens the Executive AI workspace; other roles
  // keep the AI Copilot page.
  const workspacePath = role === 'student' ? '/student/mentor' : role === 'faculty' ? '/faculty/ai-assistant' : role === 'admin' ? '/admin/ai-workspace' : `/${role}/ai-copilot`
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const scrollRef = useRef(null)
  const { mutateAsync: ask } = useAITutorRespond()
  const { data: suggestionsData } = useCopilotSuggestions(location.pathname)
  const suggestions = suggestionsData?.suggestions ?? []

  useEffect(() => {
    if (open && messages.length === 0) {
      setMessages([{ id: 'intro', role: 'assistant', text: COPIED_INTRO[role] ?? COPIED_INTRO.student }])
    }
  }, [open, role, messages.length])

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' })
  }, [messages, loading])

  const send = async (text) => {
    const trimmed = text?.trim()
    if (!trimmed || loading) return
    setMessages((m) => [...m, { id: `u_${Date.now()}`, role: 'user', text: trimmed }])
    setInput('')
    setLoading(true)
    try {
      const { reply } = await ask({ text: trimmed, threadId: 'copilot' })
      setMessages((m) => [...m, { id: `a_${Date.now()}`, role: 'assistant', text: reply }])
    } catch {
      /* Phase 27.1 (Part 22): deterministic contextual fallback — never "offline". */
      const fallback = generateTutorReply(trimmed)
      setMessages((m) => [...m, { id: `a_${Date.now()}`, role: 'assistant', text: fallback }])
      toast.info('Showing the cached contextual reply', 'Generated by the deterministic intelligence engine.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      {/* FAB */}
      <motion.button
        initial={{ scale: 0, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ type: 'spring', bounce: 0.45, delay: 0.6 }}
        onClick={() => onOpenChange(!open)}
        className="fixed bottom-6 right-6 z-[80] flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-600 via-blue-600 to-teal-500 text-white shadow-glow transition-transform hover:scale-105 active:scale-95"
        aria-label="Toggle AI Copilot"
      >
        <span className="absolute inset-0 animate-pulse-ring rounded-2xl" style={{ animationDuration: '2.8s' }} />
        {open ? <X className="relative h-6 w-6" /> : <Sparkles className="relative h-6 w-6" />}
      </motion.button>

      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0, y: 32, scale: 0.94 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 24, scale: 0.95 }}
            transition={{ type: 'spring', bounce: 0.28, duration: 0.45 }}
            className="fixed bottom-24 right-4 z-[85] flex h-[560px] w-[calc(100vw-2rem)] max-w-[400px] flex-col overflow-hidden rounded-3xl border border-slate-200/80 bg-white/95 shadow-lift backdrop-blur-2xl dark:border-slate-700 dark:bg-slate-900/95 sm:right-6"
            role="dialog"
            aria-label="MediXO Mentor chat"
          >
            {/* Header */}
            <div className="relative overflow-hidden bg-gradient-to-r from-indigo-600 via-blue-600 to-teal-500 px-4 py-3.5 text-white">
              <div className="bg-dots absolute inset-0 opacity-20" />
              <div className="relative flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/15 ring-1 ring-white/30">
                  <Bot className="h-5 w-5" />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-bold">MediXO Mentor</p>
                  <p className="flex items-center gap-1.5 text-[11px] text-white/80">
                    <span className="h-1.5 w-1.5 rounded-full bg-emerald-300" /> Online · context-aware
                  </p>
                </div>
                <button
                  onClick={() => onNavigate(workspacePath)}
                  className="rounded-xl p-2 text-white/80 transition-colors hover:bg-white/15 hover:text-white"
                  aria-label="Open full MediXO Mentor workspace"
                >
                  <Maximize2 className="h-4 w-4" />
                </button>
              </div>
            </div>

            {/* Messages */}
            <div ref={scrollRef} className="flex-1 space-y-4 overflow-y-auto scrollbar-thin px-4 py-4">
              {messages.map((m) => (
                <ChatMessage key={m.id} message={m} senderName="You" />
              ))}
              {loading && <TypingDots />}
              {!loading && messages.length <= 1 && (
                <div className="space-y-2">
                  <p className="text-[11px] font-semibold uppercase tracking-widest text-slate-400">Suggestions for this page</p>
                  {suggestions.map((s) => (
                    <button
                      key={s}
                      onClick={() => send(s)}
                      className="block w-full rounded-2xl border border-indigo-100 bg-indigo-50/60 px-3.5 py-2.5 text-left text-xs font-medium text-indigo-700 transition-all hover:border-indigo-300 hover:bg-indigo-50 dark:border-indigo-500/25 dark:bg-indigo-500/10 dark:text-indigo-300 dark:hover:bg-indigo-500/15"
                    >
                      {s}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Input */}
            <div className="border-t border-slate-200/70 p-3 dark:border-slate-800">
              <div className="flex items-end gap-2 rounded-2xl border border-slate-200 bg-white p-1.5 pl-3.5 transition-all focus-within:border-indigo-400 focus-within:ring-4 focus-within:ring-indigo-500/10 dark:border-slate-700 dark:bg-slate-950/60">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault()
                      send(input)
                    }
                  }}
                  rows={1}
                  placeholder="Ask anything…"
                  className="max-h-24 flex-1 resize-none bg-transparent py-1.5 text-sm text-slate-800 outline-none placeholder:text-slate-400 dark:text-slate-100"
                />
                <button
                  onClick={() => send(input)}
                  disabled={!input.trim() || loading}
                  className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-600 to-blue-600 text-white shadow-md shadow-indigo-500/30 transition-all hover:brightness-110 disabled:opacity-40"
                  aria-label="Send message"
                >
                  <ArrowUp className="h-4 w-4" />
                </button>
              </div>
              <p className="mt-1.5 text-center text-[10px] text-slate-400">MediXO Mentor can make mistakes — verify important answers.</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}

export { AICopilotFab }
export default AICopilotFab
