import { motion } from 'framer-motion'
import { AlertCircle, CheckCircle2, Info, Sparkles } from 'lucide-react'
import { useParentAIInsights } from '@/services'
import { PageHeader } from '@/components/shared/page-header'
import { DashboardSkeleton, ErrorState } from '@/components/shared/loading'
import { Badge } from '@/components/ui'
import { formatDate } from '@/utils/format'

const TONE_STYLES = {
  positive: { label: 'Positive', badge: 'success', icon: CheckCircle2, border: 'border-emerald-100 dark:border-emerald-500/20', glow: 'from-emerald-500/10 to-teal-500/5' },
  neutral: { label: 'Neutral', badge: 'info', icon: Info, border: 'border-sky-100 dark:border-sky-500/20', glow: 'from-sky-500/10 to-indigo-500/5' },
  warning: { label: 'Needs attention', badge: 'warning', icon: AlertCircle, border: 'border-amber-100 dark:border-amber-500/20', glow: 'from-amber-500/10 to-orange-500/5' },
}

function AIInsights() {
  const { data, isLoading, isError, refetch } = useParentAIInsights()
  const items = data?.items ?? []

  if (isLoading) return <DashboardSkeleton cards={2} />
  if (isError) return <ErrorState onRetry={() => refetch()} />

  return (
    <div>
      <PageHeader
        eyebrow="AI Insights"
        title="AI insights for you"
        description="MediXO Mentor reads months of learning signals and writes them in plain language — strengths first, always actionable."
        breadcrumbs={[{ label: 'Parent' }, { label: 'AI Insights' }]}
        actions={<Badge variant="gradient" className="px-3 py-1"><Sparkles className="h-3 w-3" /> Written for parents, not machines</Badge>}
      />

      <div className="space-y-5">
        {items.map((ins, i) => {
          const tone = TONE_STYLES[ins.tone] ?? TONE_STYLES.neutral
          return (
            <motion.div
              key={ins.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.06 }}
              className={`relative overflow-hidden rounded-3xl border bg-gradient-to-br p-7 shadow-card dark:bg-slate-900 ${tone.border} ${tone.glow}`}
            >
              <div className="flex flex-wrap items-center gap-3">
                <span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${tone.badge === 'success' ? 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300' : tone.badge === 'warning' ? 'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-300' : 'bg-sky-50 text-sky-600 dark:bg-sky-500/10 dark:text-sky-300'}`}>
                  <tone.icon className="h-5 w-5" />
                </span>
                <div className="min-w-0 flex-1">
                  <h2 className="text-[16px] font-bold text-slate-900 dark:text-white">{ins.title}</h2>
                  <p className="text-[11px] font-medium text-slate-400">{formatDate(ins.date, 'MMMM d, yyyy')}</p>
                </div>
                <Badge variant={tone.badge}>{tone.label}</Badge>
              </div>
              <p className="mt-4 max-w-3xl text-[14px] leading-relaxed text-slate-600 dark:text-slate-300">{ins.body}</p>
              <div className="mt-4 flex items-center gap-2 rounded-2xl bg-white/70 px-4 py-2.5 text-[11px] font-semibold text-slate-400 dark:bg-slate-950/40">
                <Sparkles className="h-3.5 w-3.5 text-indigo-500" />
                Generated by MediXO Mentor from attendance, grades, study patterns and teacher notes
              </div>
            </motion.div>
          )
        })}
      </div>
    </div>
  )
}

export { AIInsights }
export default AIInsights
